sudo: required

language: python

services:
  - docker

before_install:
- docker pull elasticsearch:5.5.2
- wget 	https://s3.amazonaws.com/ahalterman-geo/geonames_index.tar.gz
- tar -xzf geonames_index.tar.gz
- docker run -d -p 127.0.0.1:9200:9200 -v $(pwd)/geonames_index/:/usr/share/elasticsearch/data elasticsearch:5.5.2

install:
  - pip install -r requirements.txt

script:
  - pytest 
